### ISSUE TITLE
NameError: name 'th_dim_th_kernels' is not defined

### ISSUE THREAD

**Issue by iNLyze** [titu1994/Keras-Classification-Models#2]
Great work! I really appreciate your take on weights conversion. Yet I am having trouble to run the script. 
I defined my models by including a getter method 

`get_mymodel():
   ...
   return mymodel`

for both, th and tf dim_ordering directly in your script. I call these methods and assign the models to variables `th_dim_model` and `tf_dim_model` respectively. 
A few lines below that I get the name error cited in the title. And really, where is `th_dim_th_kernels` defined? You call it like a model: `th_dim_th_kernels.load_weights()`. I never saw any model definition for `th_dim_th_kernels`, though. 
Sorry, I might have missed something. Could you help me out?

**Comment by titu1994** [comment]
Umm can you point out which line the error is in? I pushed a lot of changes over the past couple of days, could you try downloading the script and trying again?

**Comment by iNLyze** [comment]
@titu1994, yes, that helped. Just yesterday I downloaded a new version, which worked for me. The problem seems to have been a wrong variable name in the script, from all I can tell. It works now, so closed. 
Thanks a lot.

**Comment by titu1994** [comment]
Great. Glad I could help.
