### ISSUE TITLE
When import theano model with theano weights on tensorflow backend, dimension issue occurs

### ISSUE THREAD

**Issue by ggaabe** [titu1994/Keras-Classification-Models#5]
When I have loaded a theano model with theano weights while running a tensorflow backend (to convert from Theano to Tensorflow, I receive a shape error:

`ValueError: Dimension 1 in both shapes must be equal, but are 10 and 9 for 'Assign_28' (op: 'Assign') with input shapes: [512,10], [512,9].`

When loading the same model with a theano backend, it loads perfectly. But I notice that your script to convert a model from theano to tensorflow requires a tensorflow backend. Is there any way to get a theano model to successfully load its weights on a tensorflow backend?

**Comment by titu1994** [comment]
Afaik, as of Keras 2 there is no longer any reason to port weights, as Keras handles it directly. My scripts we're for Keras 1. 

Also, weights trained on Theano for th din ordering won't work in TF dim ordering. To convert the order, TF is needed.
