### ISSUE TITLE
Keras Models w/Pretrained Weights .predict() function is too slow

### ISSUE THREAD

**Issue by pGit1** [titu1994/Keras-Classification-Models#7]
@titu1994 

Thanks for the contributions as always! With the pretrained models do you have an understanding of why .predict() is so slow for keras? Is the a way around this? K.function(etc.) type approaches don't work either.

**Comment by titu1994** [comment]
The predict function is slow only for the first batch (because it has to compile the function). K.function is used underneath the predict function. 

If it's slow, then simply put the model is too large for the GPU to process fast enough.

**Comment by pGit1** [comment]
Thanks @titu1994. Appreciate the help as always!
